### PR TITLE
Feat: Default HUD Setting & New Plugin: Traffic Advisor

### PR DESCRIPTION
**Pull request by DawsonGodin**
This will allow for a default hud setting to be saved, this way if someone finds the right place on their first time setting up a vehicle and would like that to be the same across all new profiles they won't have to manually set it in each new profile. This also includes a new plugin: Traffic Advisor, the ability to change between left, right, and middle traffic advisor by toggling extras.

This is the structure for the 'traffic_advisor' plugin for setting a traffic advisor for vehicles:

`['pd1'] = { lightbar = 1, left = { on = { add = 6, remove = 5, repair = true }, off = { add = {}, remove = { 5, 6 }, repair = true } }, right = { on = { add = 5, remove = 6, repair = true }, off = { add = {}, remove = { 5, 6 }, repair = true } }, middle = { on = { add = { 5, 6 }, remove = {}, repair = true }, off = { add = {}, remove = { 5, 6 }, repair = true } }, }`

### CODE REVIEW

**Comment by DawsonGodin** [comment]
This is the structure for the 'traffic_advisor' plugin for setting a traffic advisor for vehicles:

`['pd1'] = { lightbar = 1, left = { on = { add = 6, remove = 5, repair = true }, off = { add = {}, remove = { 5, 6 }, repair = true } }, right = { on = { add = 5, remove = 6, repair = true }, off = { add = {}, remove = { 5, 6 }, repair = true } }, middle = { on = { add = { 5, 6 }, remove = {}, repair = true }, off = { add = {}, remove = { 5, 6 }, repair = true } }, }`

**Comment by DawsonGodin** [comment]
@TrevorBarns I'd love to add this to the UI to indicate what TA direction you currently have, I was going to make the graphics myself but it'd probably be better to stick with how you've designed it so I'll leave that to you.

**Comment by TrevorBarns** [comment]
Wow, nice design, thanks for following previous design patterns and improving upon them. 👍 ❤️ 

Couple Things:
1. Plugin: I noticed was the syncing of state_ta to all players. Since we are toggling extras and those synced by the game. Is this necessary? or is it in preparation for future features? One thought would be TA syncing similar to SoundOff Blueprint or Whelen Command.  
2. HUD: Currently the hud_data KVP does not include any profile information. I think at some point it might have been included in the profile data section, but was later moved. Meaning, it should auto load default hud position regardless of new profile or old. I do not think these additions are necessary. `if save_version ~= nil` is not tied to profile either, only, if a save exists. Thoughts? Maybe the feature would be "Save HUD data separate from `save profile` functionality" for server who might not use it, and / or users who are confused by it.

Going to test right now and will look into a TA display, think that would be super cool.

**Comment by DawsonGodin** [comment]
1. Yeah the idea of syncing the TA state was to sync it at least on the UI side of things but would also work out for the smart siren plugin (I think that’s where your making the bluePrint thing?).
2. Yeah I think having the HUD data have a completely different save than a profile would be a lot more useful, I don’t really see a use case that someone would want their HUD position different per vehicle.

**Comment by TrevorBarns** [comment]
1) Sweet I'll leave that in, for future enhancements, TA syncing, etc.
2. Okay so the current stable release 3.2.2 supports this behavior, the added code is not necessary. I'll make a commit reverting the modifications leaving the TA plugin.

**Comment by DawsonGodin** [comment]
2. Well the saved HUD settings are only loaded if there's a saved profile found seen on line 169-176 of UTIL/cl_storage.lua. So I personally would suggest instead of having a default HUD setting save button to just change it to "Save HUD Settings" which will load even if there's no profile found or even if there is one found.

**Comment by TrevorBarns** [comment]
I understand now, I changed up how it works, basically pulling save function out from SaveSettings to your new function. Now both profile or "HUD save on demand" can save the hud without profile. Loadsettings also pulls same KVP.

**Pull request merged**
